# Generated by Django 3.1.7 on 2021-04-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(choices=[('django', 'Django'), ('pygame', 'Pygame'), ('unreal', 'Unreal Engine 4'), ('godot', 'Godot')], default='django', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='used_tech',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='tool',
            name='docs_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
