# Generated by Django 3.1.7 on 2021-04-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210410_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('certificate_image', models.ImageField(upload_to='images/')),
                ('certificate_pdf', models.FileField(upload_to='pdf/')),
                ('url_to_course', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.CharField(choices=[('django', 'Django'), ('php', 'PHP'), ('react', 'React.js'), ('other', 'Other'), ('pygame', 'Pygame'), ('unreal', 'Unreal Engine 4'), ('godot', 'Godot')], default='django', max_length=10),
        ),
    ]
