# Generated by Django 3.1.7 on 2021-04-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210410_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='category',
            field=models.CharField(choices=[('W', 'Web'), ('G', 'Game')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='certificate',
            name='projects',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
